### ISSUE TITLE
Modify CRD Kind from ExternalWorkload to VM

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/kvm-service#17]
Currently the CRD for VM in KVMSOperator is configured/named as KubeArmorExternalWorkload. It needs to be changed to VM instead. 

The final name of the CRD should be **KubeArmorVm**.

**Comment by nyrahul** [comment]
> 
> The final name of the CRD should be **KubeArmorVm**.

Lets call it, `KubeArmorVirtualMachine` (not `KubeArmorVm`). Short form of `kvm` is ok.

**Comment by seswarrajan** [comment]
Also the current option to get the list of VMs is kew.
This needs to be renamed to kvm

**Comment by vaibhavmew** [comment]
I can take this up.

**Comment by vaibhavmew** [comment]
Which fields do we need for **kubectl get kvm -o wide** other than Name & Age.

**Comment by seswarrajan** [comment]
> Which fields do we need for **kubectl get kvm -o wide** other than Name & Age.

Hi @vaibhavmew We can focus only on the renaming the KubeArmorExternalWorkload to KubeArmorVirtualMachine
We can take **-o -wide** on a separate issue.

**Comment by seswarrajan** [comment]
The changes are complete and merged into dev
